apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-matchlabels
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev  # Matches Pods that have the label 'env=dev'
  template:
    metadata:
      labels:
        env: dev
        tier: frontend
    spec:
      containers:
        - image: nginx
          name: frontend-container